In [105]:
import pandas as pd
import numpy as np
import csv

In [106]:
#Limpiar valores vacios 
df = pd.read_csv('airports.csv',header=0,encoding='utf-8',na_filter=False)
df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11,NA,US,US-PA,Bensalem,no,00A,,00A,,,
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435,NA,US,US-KS,Leoti,no,00AA,,00AA,,,
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450,NA,US,US-AK,Anchor Point,no,00AK,,00AK,,,
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820,NA,US,US-AL,Harvest,no,00AL,,00AL,,,
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80,NA,US,US-AK,King Salmon,no,00AN,,00AN,,,

In [107]:
df['elevation_ft'] = pd.to_numeric(df['elevation_ft'], errors='coerce')
df.loc[96].elevation_ft

nan

In [108]:
for column in df.columns:
    if df[column].dtype == object:  # Check if column contains text
        df[column] = df[column].fillna('').replace('', 'NULL')
    else:  # Column contains numeric values
        df[column] = df[column].fillna(0)

        
        
df.loc[96].elevation_ft

0.0

In [109]:
df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NA,US,US-PA,Bensalem,no,00A,NULL,00A,NULL,NULL,NULL
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NA,US,US-KS,Leoti,no,00AA,NULL,00AA,NULL,NULL,NULL
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NA,US,US-AK,Anchor Point,no,00AK,NULL,00AK,NULL,NULL,NULL
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NA,US,US-AL,Harvest,no,00AL,NULL,00AL,NULL,NULL,NULL
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NA,US,US-AK,King Salmon,no,00AN,NULL,00AN,NULL,NULL,NULL

In [110]:
df.to_csv('cleanAirports.csv', index=False)

In [111]:
#agregar quotes
df = pd.read_csv('cleanAirports.csv',header=0,encoding='utf-8',na_filter=False)
df.to_csv('quotedAirports.csv', index=False, quoting=csv.QUOTE_NONNUMERIC, quotechar='"')

In [112]:
df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NA,US,US-PA,Bensalem,no,00A,NULL,00A,NULL,NULL,NULL
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NA,US,US-KS,Leoti,no,00AA,NULL,00AA,NULL,NULL,NULL
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NA,US,US-AK,Anchor Point,no,00AK,NULL,00AK,NULL,NULL,NULL
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NA,US,US-AL,Harvest,no,00AL,NULL,00AL,NULL,NULL,NULL
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NA,US,US-AK,King Salmon,no,00AN,NULL,00AN,NULL,NULL,NULL